/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.HeadlessException;
import java.io.FileInputStream;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Cliente extends javax.swing.JFrame {
 FileInputStream fis;
    Connection con;
    ResultSet r;
    CallableStatement cst;

    public Cliente() {
        initComponents();
         try {
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection("jdbc:postgresql://localhost/farmacia",
                    "postgres", "1234");

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        cbsexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bningresar = new javax.swing.JButton();
        bnmodificacion = new javax.swing.JButton();
        bnvolver = new javax.swing.JButton();
        bneliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cedula: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 61, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 108, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Direccion:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 192, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sexo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 234, -1, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 112, 107, -1));

        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 65, 107, -1));

        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 154, 111, -1));

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 196, 111, -1));

        cbsexo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cbsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Masculino", "Femenino" }));
        jPanel1.add(cbsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 235, 111, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proyecto2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 240, 250));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Registro de Clientes");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 36, 23));

        bningresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bningresar.setText("INGRESAR");
        bningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bningresarActionPerformed(evt);
            }
        });
        jPanel1.add(bningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 301, -1, -1));

        bnmodificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnmodificacion.setText("MODIFICACION");
        bnmodificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnmodificacionActionPerformed(evt);
            }
        });
        jPanel1.add(bnmodificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 301, -1, -1));

        bnvolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnvolver.setText("VOLVER");
        bnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnvolverActionPerformed(evt);
            }
        });
        jPanel1.add(bnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 301, 112, -1));

        bneliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bneliminar.setText("ELIMINAR");
        bneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 301, 112, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char c=evt.getKeyChar();
				if(Character.isDigit(c)){
					getToolkit().beep();
					evt.consume();
  JOptionPane.showMessageDialog(null, "Solo puede ingresar letras");// TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyTyped
    }
    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        char d= evt.getKeyChar();
				if(Character.isLetter(d)){
				getToolkit().beep();
				evt.consume();
   JOptionPane.showMessageDialog(null, "Solo puede ingresar números");// TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaKeyTyped
    }
    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
    }//GEN-LAST:event_txtdireccionKeyTyped
    
    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
       char m= evt.getKeyChar();
				if(Character.isLetter(m)){
				getToolkit().beep();
				evt.consume();
   JOptionPane.showMessageDialog(null, "Solo puede ingresar números");  // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoKeyTyped
    }
    private void bningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bningresarActionPerformed
        if (txtcedula.getText().length() == 0) {

            JOptionPane.showMessageDialog(null, "NECESITA INGRESAR DATOS");
        } else {
            try {
                String sql = "INSERT INTO cliente(cedula,nombre,direccion,telefono,sexo) VALUES (?,?,?,?,?)";

                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, txtcedula.getText());
                ps.setString(2, txtnombre.getText());
                ps.setString(3, txtdireccion.getText());
                ps.setString(4, txttelefono.getText());
                  ps.setString(5, cbsexo.getSelectedItem().toString());

                ps.execute();
                ps.close();

                JOptionPane.showMessageDialog(rootPane, "Guardado correctamente");
                this.txtnombre.setText("");
                this.txtcedula.setText("");
                this.txtdireccion.setText("");
                this.txttelefono.setText("");
                 cbsexo.setSelectedIndex(0);
            } catch (SQLException | NumberFormatException | HeadlessException x) {
                JOptionPane.showMessageDialog(rootPane, "ya existe el numero de cedula " );
            }
        }             // TODO add your handling code here:
    }//GEN-LAST:event_bningresarActionPerformed

    private void bnmodificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnmodificacionActionPerformed
        String marca= this.txtcedula.getText();
        String ram= this.txtnombre.getText();
        String procesador = this.txtdireccion.getText();
        String disco = this.txttelefono.getText();
 String sexo = this.cbsexo.getSelectedItem().toString();
        try {
            cst = con.prepareCall("UPDATE cliente SET nombre=?,direccion=?,telefono=?,sexo=? WHERE"+ " cedula=?");
            // cst.setString(1, marca);
            cst.setString(1, ram);
            cst.setString(2, procesador);
            cst.setString(3, disco);
             cst.setString(4, sexo);
            cst.setString(5, marca);
            int rpta = cst.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Cliente Modificado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.txtnombre.setText("");
                this.txtcedula.setText("");
                this.txtdireccion.setText("");
                this.txttelefono.setText("");
 cbsexo.setSelectedIndex(0);
            } else {

                JOptionPane.showMessageDialog(this, "Error al modificar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }       // TODO add your handling code here:
    }//GEN-LAST:event_bnmodificacionActionPerformed

    private void bnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnvolverActionPerformed
Ventana1 jFrame = new Ventana1();//"Frame2" es el nombre que tu le pusiste a tu 2do jframe
                jFrame.setVisible(true); 
                dispose();// TODO add your handling code here:
    }//GEN-LAST:event_bnvolverActionPerformed

    private void bneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bneliminarActionPerformed
        String marca=this.txtcedula.getText();
        try {
            cst=con.prepareCall("Delete from cliente where cedula=?");
            cst.setString(1, marca);
            int rpta=cst.executeUpdate();

            if(rpta==1){
                JOptionPane.showMessageDialog(this, "Cliente Eliminado","Aviso",JOptionPane.INFORMATION_MESSAGE);
                this.txtnombre.setText("");
                this.txtcedula.setText("");
                this.txtdireccion.setText("");
                this.txttelefono.setText("");
 cbsexo.setSelectedIndex(0);
            }else {
                JOptionPane.showMessageDialog(this, "Cliente No Eliminado","Aviso",JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (Exception e) {JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_bneliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  if (txtcedula.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(null, "NECESITA INGRESAR UN CODIGO");

        } else {

            String codigo = (this.txtcedula.getText());
            try {
                cst = con.prepareCall("select cedula,nombre,direccion,telefono,sexo from cliente where cedula=? ");
                cst.setString(1, codigo);
                r = cst.executeQuery();

                if (r.next()) {

                    JOptionPane.showMessageDialog(this, "Encontrado!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    this.txtcedula.setText(r.getString(1));
                    this.txtnombre.setText(r.getString(2));
                    this.txtdireccion.setText(r.getString(3));
                    this.txttelefono.setText(r.getString(4));
                    this.cbsexo.setSelectedItem(r.getString(5).toString());
                    
                } else {
                   
                    JOptionPane.showMessageDialog(this, "Cliente No Encontrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                }

            } catch (Exception e) {
                // JOptionPane.showMessageDialog(this, e.toString());
                JOptionPane.showMessageDialog(this, "Cliente No Encontrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bneliminar;
    private javax.swing.JButton bningresar;
    private javax.swing.JButton bnmodificacion;
    private javax.swing.JButton bnvolver;
    private javax.swing.JComboBox<String> cbsexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
